Three Line Example:
    args:
        approx_freq_ge: 100
        approx_type: slognorm
        bs: 1
        last_distortion: None
        last_sev_calc: discrete
        log2: 14
        padding: 1
        remove_fuzz: false
        tilt_amount: 0
    spec:
    -   name: single
        attachment: 0
        el: 0
        en: 10
        freq_a: 0
        freq_b: 0
        freq_name: poisson
        limit: .inf
        lr: 0
        mix_wt: 1
        premium: 0
        sev_cv: 0.75
        sev_mean: 100
        sev_name: lognorm
    -   name: mixed
        attachment: 0
        el: 0
        en: 10
        freq_a: 0
        freq_b: 0
        freq_name: poisson
        limit: 250
        lr: 0
        mix_wt: !!python/tuple [0.2, 0.2, 0.2, 0.2, 0.2]
        premium: 0
        sev_cv: !!python/tuple [0.2, 0.4, 0.6, 0.8, 1.0]
        sev_mean: 100
        sev_name: lognorm
    -   name: sublines
        attachment:
        -   0
        -   0
        -   100
        -   50
        el: 0
        en:
        -   10
        -   10
        -   10
        -   10
        freq_a: 0
        freq_b: 0
        freq_name: poisson
        limit:
        -   .inf
        -   100
        -   .inf
        -   100
        lr: 0
        mix_wt: 1
        name: sublines
        premium: 0
        sev_a: 0.75
        sev_b: 0
        sev_cv: 0
        sev_loc: 0
        sev_mean: 100
        sev_name: lognorm
Single:
    args:
        approx_freq_ge: 100
        approx_type: slognorm
        bs: 1
        last_distortion: None
        last_sev_calc: discrete
        log2: 14
        padding: 1
        remove_fuzz: false
        tilt_amount: 0
    spec:
    -   name: single
        attachment: 0
        el: 0
        en: 10
        freq_a: 0
        freq_b: 0
        freq_name: poisson
        limit: .inf
        lr: 0
        mix_wt: 1
        premium: 0
        sev_cv: 0.75
        sev_mean: 100
        sev_name: lognorm
Mixed:
    args:
        approx_freq_ge: 100
        approx_type: slognorm
        bs: 1
        last_distortion: None
        last_sev_calc: discrete
        log2: 14
        padding: 1
        remove_fuzz: false
        tilt_amount: 0
    spec:
    -   name: mixed
        attachment: 0
        el: 0
        en: 10
        freq_a: 0
        freq_b: 0
        freq_name: poisson
        limit: 250
        lr: 0
        mix_wt:
        -   0.2
        -   0.2
        -   0.2
        -   0.2
        -   0.2
        premium: 0
        sev_cv:
        -   0.2
        -   0.4
        -   0.6
        -   0.8
        -   1.0
        sev_mean: 100
        sev_name: lognorm
Sublines:
    args:
        approx_freq_ge: 100
        approx_type: slognorm
        bs: 1
        last_distortion: None
        last_sev_calc: discrete
        log2: 14
        padding: 1
        remove_fuzz: false
        tilt_amount: 0
    spec:
    -   name: sublines
        attachment:
        -   0
        -   0
        -   100
        -   50
        el: 0
        en:
        -   10
        -   10
        -   10
        -   10
        freq_a: 0
        freq_b: 0
        freq_name: poisson
        limit:
        -   .inf
        -   100
        -   .inf
        -   100
        lr: 0
        mix_wt: 1
        name: sublines
        premium: 0
        sev_a: 0.75
        sev_b: 0
        sev_cv: 0
        sev_loc: 0
        sev_mean: 100
        sev_name: lognorm
